version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: iskra_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: IskraAnalyticsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/IskraAnalytics/IskraAnalytics.API
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  pgdata: