version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: iskra_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: IskraAnalyticsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/IskraAnalytics
      dockerfile: IskraAnalytics.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
    - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=IskraAnalyticsDb;Username=user;Password=123;
    depends_on:
      - db
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "80:3000"
    depends_on:
    - backend

volumes:
  pgdata: