version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: iskra_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: IskraAnalyticsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/IskraAnalytics/IskraAnalytics.API/Dockerfile
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - backend

volumes:
  pgdata: